Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
SR_dut=pd.Series(index=QE_dut.index,
            data=[QE_dut.loc[i,'QE']*e*i*0.000000001/(h*c) for i in QE_dut.index])
SR_cal=pd.Series(index=QE_cal.index,
            data=[QE_cal.loc[i,'QE']*e*i*0.000000001/(h*c) for i in QE_cal.index])
plt.plot(SR_DUT, 
         linewidth=2,
        label='DUT')
plt.plot(SR_cal, 
         linewidth=2,
        label='reference')
plt.legend()
plt.ylabel('Spectral response, $SR$')
plt.xlabel(r'Wavelength, $\lambda$ (nm)');
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 5[0m
[1;32m      1[0m SR_dut[38;5;241m=[39mpd[38;5;241m.[39mSeries(index[38;5;241m=[39mQE_dut[38;5;241m.[39mindex,
[1;32m      2[0m             data[38;5;241m=[39m[QE_dut[38;5;241m.[39mloc[i,[38;5;124m'[39m[38;5;124mQE[39m[38;5;124m'[39m][38;5;241m*[39me[38;5;241m*[39mi[38;5;241m*[39m[38;5;241m0.000000001[39m[38;5;241m/[39m(h[38;5;241m*[39mc) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m QE_dut[38;5;241m.[39mindex])
[1;32m      3[0m SR_cal[38;5;241m=[39mpd[38;5;241m.[39mSeries(index[38;5;241m=[39mQE_cal[38;5;241m.[39mindex,
[1;32m      4[0m             data[38;5;241m=[39m[QE_cal[38;5;241m.[39mloc[i,[38;5;124m'[39m[38;5;124mQE[39m[38;5;124m'[39m][38;5;241m*[39me[38;5;241m*[39mi[38;5;241m*[39m[38;5;241m0.000000001[39m[38;5;241m/[39m(h[38;5;241m*[39mc) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m QE_cal[38;5;241m.[39mindex])
[0;32m----> 5[0m plt[38;5;241m.[39mplot([43mSR_DUT[49m, 
[1;32m      6[0m          linewidth[38;5;241m=[39m[38;5;241m2[39m,
[1;32m      7[0m         label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mDUT[39m[38;5;124m'[39m)
[1;32m      8[0m plt[38;5;241m.[39mplot(SR_cal, 
[1;32m      9[0m          linewidth[38;5;241m=[39m[38;5;241m2[39m,
[1;32m     10[0m         label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mreference[39m[38;5;124m'[39m)
[1;32m     11[0m plt[38;5;241m.[39mlegend()

[0;31mNameError[0m: name 'SR_DUT' is not defined

