Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for spectra in ['AM0', 'AM1.5G', 'AM1.5D']:
    irradiance=np.trapezoid(datafile[spectra], x = datafile.index)
    print('Total irradiance in ' + spectra + ' = ' + str(irradiance.round(1)) + ' W/m2')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m [38;5;28;01mfor[39;00m spectra [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mAM0[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mAM1.5G[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mAM1.5D[39m[38;5;124m'[39m]:
[0;32m----> 2[0m     irradiance[38;5;241m=[39m[43mnp[49m[38;5;241;43m.[39;49m[43mtrapezoid[49m(datafile[spectra], x [38;5;241m=[39m datafile[38;5;241m.[39mindex)
[1;32m      3[0m     [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mTotal irradiance in [39m[38;5;124m'[39m [38;5;241m+[39m spectra [38;5;241m+[39m [38;5;124m'[39m[38;5;124m = [39m[38;5;124m'[39m [38;5;241m+[39m [38;5;28mstr[39m(irradiance[38;5;241m.[39mround([38;5;241m1[39m)) [38;5;241m+[39m [38;5;124m'[39m[38;5;124m W/m2[39m[38;5;124m'[39m)

File [0;32m/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/numpy/__init__.py:333[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    330[0m     [38;5;124m"[39m[38;5;124mRemoved in NumPy 1.25.0[39m[38;5;124m"[39m
[1;32m    331[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mTester was removed in NumPy 1.25.[39m[38;5;124m"[39m)
[0;32m--> 333[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124mmodule [39m[38;5;132;01m{!r}[39;00m[38;5;124m has no attribute [39m[38;5;124m"[39m
[1;32m    334[0m                      [38;5;124m"[39m[38;5;132;01m{!r}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;18m__name__[39m, attr))

[0;31mAttributeError[0m: module 'numpy' has no attribute 'trapezoid'

